version: "3.9"
services:
  statuschecker:
    image: statuschecker
    ports:
      - "8080:8080"
    environment:
      APP_DBHOST: db
  db:
    image: postgres:11.10-alpine
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: statuschecker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: statuschecker
